  nginx_vhosts:
  - listen: "443" # default: "80"
    server_name: "qa.example.com" # default: N/A
    # root: "/var/www/dev.example.com" # default: N/A
    # index: "index.html index.htm" # default: "index.html index.htm"
    filename: "qa.example.com-https.conf" # Can be used to set the filename of the vhost file.
#   # Properties that are only added if defined:
#   server_name_redirect: "www.example.com" # default: N/A
#   error_page: ""
#   access_log: ""
#   error_log: ""
    extra_parameters: | # Can be used to add extra config blocks (multiline).
      proxy_connect_timeout 600;
      proxy_send_timeout 600;
      proxy_read_timeout 600;
      send_timeout 600;

      gzip on;
      gzip_types text/plain text/css text/html application/javascript application/json;
      gzip_static on;

      ssl_certificate        /etc/ssl/certs/example.com.crt;
      ssl_certificate_key    /etc/ssl/certs/example.com.key;
      ssl on;
      ssl_protocols       SSLv2 SSLv3 TLSv1 TLSv1.1 TLSv1.2;
      ssl_ciphers  ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP;

      location /dss {
        rewrite ^/dss/(.*)$ /$1 break;
        proxy_pass http://qadssusa;
      }

      location / {
        proxy_pass https://qacontentusa;
      }
#   template: "" # Can be used to override the `nginx_vhost_template` per host.
#   state: "absent" # To remove the vhost configuration.

  - listen: "80"
    server_name:    "qa.example.com"
    filename: "qa.example.com-http.conf"
    extra_parameters: |
      return         302 https://$server_name$request_uri;

  nginx_upstreams:
  - name: qadssusa
    strategy: "ip_hash" # "least_conn", etc.
    keepalive: 16 # optional
    servers: {
      "qa-swarm-usa-1.example.com:8483"
    }

  - name: qacontentusa
    strategy: "ip_hash" # "least_conn", etc.
    keepalive: 16 # optional
    servers: {
      "qa-usa.example.com:443"
    }
